# This file was generated by GoReleaser. DO NOT EDIT.
cask "example-zig" do
  name "example-zig"
  desc "Example zig release."
  homepage "https://goreleaser.com"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "example-zig"

  on_macos do
    url "https://github.com/goreleaser/example-zig/releases/download/v#{version}/example_Darwin_all.tar.gz"
    sha256 "7dbddf1160ef58ac90d18253ba6a2740241c40a9f9ee4131836144f1f2bf1b1b"
  end

  on_linux do
    on_intel do
      url "https://github.com/goreleaser/example-zig/releases/download/v#{version}/example_Linux_x86_64.tar.gz"
      sha256 "c75b7bc67a724a315012f72ac4e673f4bd59cffdc4dbbd4eaffa8edc9b4cc4b7"
    end
    on_arm do
      url "https://github.com/goreleaser/example-zig/releases/download/v#{version}/example_Linux_arm64.tar.gz"
      sha256 "91a81c707b97a96f9d81a0ba343847315e417d03613986cae2c73304565dd192"
    end
  end

  # No zap stanza required
end
