# This file was generated by GoReleaser. DO NOT EDIT.
cask "example-zig" do
  version "0.2.1"

  on_macos do
    url "https://github.com/goreleaser/example-zig/releases/download/v#{version}/example_Darwin_all.tar.gz"
    sha256 "380c8872750678308e937933c447f3da27eaaf094b1716f7cd20912ce23cc954"
  end

  on_linux do
    on_intel do
      url "https://github.com/goreleaser/example-zig/releases/download/v#{version}/example_Linux_x86_64.tar.gz"
      sha256 "6081ebe63654c6f86194784a317683d7800b6a61b280d943f267ee5b383afcb0"
    end
    on_arm do
      url "https://github.com/goreleaser/example-zig/releases/download/v#{version}/example_Linux_arm64.tar.gz"
      sha256 "bcdf0c2b40a816c949a1eadf813b170cbfaeca48c56730ae35e0c094fafa9c57"
    end
  end

  name "example-zig"
  desc "Example zig release."
  homepage "https://goreleaser.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "example-zig"

  # No zap stanza required

end
