# This file was generated by GoReleaser. DO NOT EDIT.
cask "example-zig" do
  version "0.2.2"

  on_macos do
    url "https://github.com/goreleaser/example-zig/releases/download/v#{version}/example_Darwin_all.tar.gz"
    sha256 "d261978f0394dcd6ec52a07d2b37fe2902fd7b746f4de32960758afdf39c0206"
  end

  on_linux do
    on_intel do
      url "https://github.com/goreleaser/example-zig/releases/download/v#{version}/example_Linux_x86_64.tar.gz"
      sha256 "bbfe1005dff3a671f6380940ceaff61f6e8f97f99106d85420fee12b5b76ffe4"
    end
    on_arm do
      url "https://github.com/goreleaser/example-zig/releases/download/v#{version}/example_Linux_arm64.tar.gz"
      sha256 "8482aeec6f972a1d5fbc9494294735747c256e187aa2207d74af3a4c822deadf"
    end
  end

  name "example-zig"
  desc "Example zig release."
  homepage "https://goreleaser.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "example-zig"

  # No zap stanza required

end
