# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ExampleRust < Formula
  desc "Example rust release."
  homepage "https://goreleaser.com"
  version "0.1.5"
  license "MIT"

  on_macos do
    url "https://github.com/goreleaser/example-rust/releases/download/v0.1.5/example_Darwin_all.tar.gz"
    sha256 "49f5454f76e33dec168be126f6f61ea447a94060d497502df4f28366b3e794be"

    define_method(:install) do
      bin.install "example"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/goreleaser/example-rust/releases/download/v0.1.5/example_Linux_x86_64.tar.gz"
      sha256 "031ecde831d4155dc9e1d4581e55848d335954684e8318758b5433554ad71fcf"
      define_method(:install) do
        bin.install "example"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/goreleaser/example-rust/releases/download/v0.1.5/example_Linux_arm64.tar.gz"
      sha256 "9dccdb280e629a3e4f0f5ff510713c14d56ef919918602244111e96e77e172d8"
      define_method(:install) do
        bin.install "example"
      end
    end
  end
end
