# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ExampleZig < Formula
  desc "Example zig release."
  homepage "https://goreleaser.com"
  version "0.1.5"
  license "MIT"

  on_macos do
    url "https://github.com/goreleaser/example-zig/releases/download/v0.1.5/example_Darwin_all.tar.gz"
    sha256 "61d3cc3d837a1d0c393d1b1ccc9437e5eb6dce1b9480988d3e15d90e6800d1f8"

    def install
      bin.install "example"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/goreleaser/example-zig/releases/download/v0.1.5/example_Linux_arm64.tar.gz"
        sha256 "e84585ca4adafdc557b441c85de7b35e73447acdb488614cee23aa340a2d0b30"

        def install
          bin.install "example"
        end
      end
    end
  end
end
